name = "RushHour"
uuid = "ab4d6a7e-3342-4f70-99d7-d1c2b2aab356"
authors = ["JeroenOlieslagers <jo2229@nyu.edu>"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PolyLog = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
Polylogarithms = "43cc4a2f-1a2b-4fbb-87e3-95c794af13de"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
